### ISSUE TITLE
Could you share the code for computing energy, power, and efficiency metrics?

### ISSUE THREAD

**Issue by VoXuanThuy** [saic-fi/edgevit#2]
Thank you for your great work. I have a concern related to the efficiency metrics. Could you share the code for computing energy, power, and efficiency metrics?

I'm looking forward to hearing from you.

**Comment by vaenyr** [comment]
Hi,
We were using our generic benchmarking tool that was developed for the purpose of writing another paper: https://dl.acm.org/doi/10.1145/3487552.3487863
I'm not sure what the status of this tool is regarding open-sourcing but it's rather doubtful we can share the code now.
However, if helpful I'm happy to answer any questions or provide details needed to reproduce results.
Thanks

**Comment by vaenyr** [comment]
Hi, do you have any specific questions or concerns? I would be happy to discuss things - admittedly, there are some tricky parts about energy/power computation but without any indication what part of the system might be problematic I'm afraid I can't help much. I might also be able to share some parts of the code if I know what you'd be interested in, specifically. I might also be able to share raw measurements and/or specific models that we benchmarked. But in any way, I would need to either know what would help you specifically, or what are your concerns exactly. Thanks

**Comment by VoXuanThuy** [comment]
Thank you for your response. After carefully reading your paper and comments, I catch your process and computation. Now, there is no concern about it. So, I will close this issue.
